Update sync.yml

diff --git a/.github/workflows/sync.yml b/.github/workflows/sync.yml
--- a/.github/workflows/sync.yml
+++ b/.github/workflows/sync.yml
@@ -1,28 +1,34 @@
-name: Sync Fork
+name: Upstream Sync
+
+permissions:
+    contents: write
 
 on:
-  schedule:
-    - cron: '*/1 * * * *'  #  每周日的午夜（UTC）
-  workflow_dispatch:  # 允许手动触发
+    schedule:
+        - cron: "0 0 * * *"
+    workflow_dispatch:
 
 jobs:
-  sync:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
-        with:
-          repository: qist/tvbox
-          token: ${{ secrets.MY_GITHUB_TOKEN }}
-          path: upstream
+    sync_with_upstream:
+        name: Sync with Upstream
+        runs-on: ubuntu-latest
+        if: ${{ github.event.repository.fork }}
 
-      - name: Sync
-        run: |
-          cd ./upstream
-          git config --global user.name "MrJiangLong"
-          git config --global user.email "njutjl@126.com"
-          git remote add upstream https://github.com/qist/tvbox.git
-          git fetch upstream
-          git checkout master  # 或者你想要同步的分支
-          git merge upstream/master  # 或者你想要同步的分支
-          git push origin master  # 或者你想要同步的分支
+        steps:
+            - name: Checkout target repo
+              uses: actions/checkout@v3
+
+            - name: Sync Upstream
+              uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
+              with:
+                  target_repo_token: ${{ secrets.MY_GITHUB_TOKEN }}
+                  upstream_sync_repo: qist/tvbox
+                  upstream_sync_branch: main
+                  target_sync_branch: main
+                  test_mode: false
+
+            - name: Check for Failure
+              if: failure()
+              run: |
+                  echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork."
+                  exit 1
